FROM 192.168.1.112:5000/rckr-geospatial-vaphana

ADD . /srv/code

RUN chmod -R a+rwX /srv/code/

WORKDIR /srv/code
RUN R -e 'remotes::install_github("hrbrmstr/hrbrthemes")'
RUN R -e 'remotes::install_local(upgrade="always")'

EXPOSE 3838

CMD ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');reseptilaakesovellus::run_app()"]
