# This is a basic workflow to help you get started with Actions

name: Deploy on push master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build image
      - name: Build image
        run: docker build -t pullrequestimage .
      # run the image (but supply the TESTNAME in stead of MASTERNAME, so the
      # app ends up in a different place.
      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{secrets.SHINY_ACC_NAME}}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          -e MASTERNAME=${{secrets.MASTERNAME}}
          pullrequestimage
